Add project design
saba024/Front-end_labs pull request #2
Opened 2021-04-03 15:46 UTC by saba024

Project - Group expense app

https://wireframepro.mockflow.com/view/Mb5bb587c553ce60300a6b26d447ba69c1617117186993

2021-04-05 14:57 UTC, gmltA requested changes
У вас няверная паслядоўнасць загалоўкаў, шмат якія элементы не адпавядаюць свайму семантычнаму сэнсу (`nav`, частка `div`).

2021-04-07 14:16 UTC, saba024 commented
I have fixed my design

2021-04-19 20:17 UTC, gmltA reviewed
Зараз вы нешта незразумелае робіце са спісамі замест таго, каб выкарыстаць табліцы.

2021-04-21 16:53 UTC, saba024 commented
fix it

2021-04-25 15:39 UTC, gmltA commented
Зараз магу прапанаваць <kbd>6</kbd>. Будзем выпраўляць далей?

2021-04-25 15:42 UTC, saba024 commented
6 хватит.

2021-04-26 14:19 UTC, gmltA approved these changes

2021-04-26 20:12 UTC, merged