Splitwiseclone html
saba024/Front-end_labs pull request #3
Opened 2021-05-10 20:54 UTC by saba024

Add html and css.

2021-05-10 20:57 UTC, saba024 commented
https://saba024.github.io/Front-end_labs/index.html

2021-05-12 19:14 UTC, gmltA requested changes

2021-05-12 19:14 UTC, gmltA commented on index.html
> +							<a class="ru">Russian</a>
How's that a link?

2021-05-12 19:14 UTC, gmltA commented on index.html
> +	<header class="header">
![image](https://user-images.githubusercontent.com/138737/118031371-1fbaa700-b36f-11eb-8f2a-50455c5cf39c.png)

Everything went wrong!

2021-05-12 19:14 UTC, gmltA commented on index.html
> +				<a href="#tab_01" class="tabs_item"><span class="tab_name">Expenses</span></a>
This is also not a link.

2021-05-12 19:14 UTC, gmltA commented on index.html
> +								<div class="btn_edit">Edit</div>
These should be `button`s.

2021-05-12 19:14 UTC, gmltA commented on index.html
> +					<div class="view_wrap expense-list">
If it is a list, why do you use `div`?

2021-05-12 19:14 UTC, gmltA commented on index.html
> +			<label for="amount" class="amount">Amount</label>
Labels for what?

2021-05-14 17:42 UTC, gmltA requested changes

2021-05-14 17:42 UTC, gmltA commented on index.html
> +					<ul class="view_wrap expense-list">
And where are your list items then?

2021-05-14 17:42 UTC, gmltA commented on index.html
> +			<label class="amount">Amount</label>
U kidding me? It is also wrong. Labels are meant for inputs!

2021-05-14 17:43 UTC, gmltA commented
![image](https://user-images.githubusercontent.com/138737/118308777-07749480-b4f5-11eb-9d70-dbe47b2ac4b9.png)

This is still broken. Plus you are not allowed to use `float`.

2021-05-15 19:54 UTC, gmltA requested changes

2021-05-15 19:54 UTC, gmltA commented on index.html
> +			<div class="category-select" id="category-select" >
The heck is this?

2021-05-15 19:54 UTC, gmltA commented on index.html
> +			<button class="share_equally" id="shared">share equally</button>
And this.

2021-05-18 19:28 UTC, gmltA approved these changes
Okay. That's a <kbd>6</kbd>.

2021-05-30 21:54 UTC, merged